name: Finalize Release

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  finalize-release:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'release/') &&
      contains(github.event.pull_request.labels.*.name, 'release')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Get version from manifest
        id: version
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Release version: v$VERSION"

      - name: Create release assets
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          
          # Create a clean directory for the extension
          mkdir -p "warren-preview-extension-v$VERSION"
          
          # Copy extension files (exclude development files)
          cp manifest.json "warren-preview-extension-v$VERSION/"
          cp styles.css "warren-preview-extension-v$VERSION/"
          cp -r scripts "warren-preview-extension-v$VERSION/"
          cp -r images "warren-preview-extension-v$VERSION/"
          cp README.md "warren-preview-extension-v$VERSION/"
          
          # Create zip archive
          zip -r "warren-preview-extension-v$VERSION.zip" "warren-preview-extension-v$VERSION"
          
          # Create tar.gz archive
          tar -czf "warren-preview-extension-v$VERSION.tar.gz" "warren-preview-extension-v$VERSION"
          
          echo "Created release assets:"
          ls -la *.zip *.tar.gz

      - name: Update and publish release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          TAG="v$VERSION"
          
          # Check if release exists and update it
          if gh release view "$TAG" >/dev/null 2>&1; then
            echo "Updating existing draft release $TAG"
            
            # Upload assets to the existing release
            gh release upload "$TAG" "warren-preview-extension-v$VERSION.zip" --clobber
            gh release upload "$TAG" "warren-preview-extension-v$VERSION.tar.gz" --clobber
            
            # Publish the release (removes draft status)
            gh release edit "$TAG" --draft=false
            
            echo "✅ Release $TAG has been published with assets!"
          else
            echo "No existing draft release found for $TAG"
            echo "Creating new release..."
            
            # Create release notes
            RELEASE_NOTES="## What's Changed in v$VERSION

### Installation
1. Download the extension files from the assets below
2. Open Chrome and go to \`chrome://extensions/\`  
3. Enable \"Developer mode\"
4. Click \"Load unpacked\" and select the extracted folder

### Extension Files
- \`warren-preview-extension-v$VERSION.zip\` - Ready-to-use extension package
- \`warren-preview-extension-v$VERSION.tar.gz\` - Alternative archive format

**Full Changelog**: https://github.com/${{ github.repository }}/compare/v${{ github.event.pull_request.base.sha }}...${{ github.sha }}"

            # Create and publish release with assets
            gh release create "$TAG" \
              "warren-preview-extension-v$VERSION.zip" \
              "warren-preview-extension-v$VERSION.tar.gz" \
              --title "$TAG" \
              --notes "$RELEASE_NOTES" \
              --generate-notes
          fi

      - name: Clean up release branch
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          echo "Cleaning up release branch: $BRANCH_NAME"
          git push origin --delete "$BRANCH_NAME" || echo "Branch already deleted"

      - name: Output summary
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          echo "## Release v$VERSION Published! 🚀" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Tag**: v$VERSION" >> $GITHUB_STEP_SUMMARY  
          echo "- **Assets**: Extension packages uploaded" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: Published and ready for download" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Release URL:" >> $GITHUB_STEP_SUMMARY
          echo "https://github.com/${{ github.repository }}/releases/tag/v$VERSION" >> $GITHUB_STEP_SUMMARY
